### ISSUE TITLE
Improve error message in case of HTTP request error

### ISSUE THREAD

**Issue by jugmac00** [florimondmanca/asgi-sitemaps#1]
Hi, just read your announcement on Twitter and gave it a try...

```
❯ python -m sitemaps https://www.apis.de
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/sitemaps/__main__.py", line 6, in <module>
    sys.exit(anyio.run(main, sys.argv[1:]))
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/anyio/__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 99, in run
    raise exception
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/sitemaps/_main.py", line 89, in main
    urls = await crawl(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/sitemaps/_crawl.py", line 31, in crawl
    await _add(root_url, parent_url="", config=config, state=state)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 375, in __aexit__
    raise exceptions[0]
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 398, in _run_wrapped_task
    await func(*args)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/sitemaps/_crawl.py", line 55, in _process
    response = await config.client.get(url)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1305, in get
    return await self.request(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1147, in request
    response = await self.send(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1168, in send
    response = await self.send_handling_redirects(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1195, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpx/_client.py", line 1264, in send_single_request
    ) = await transport.request(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 152, in request
    response = await connection.request(
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_async/connection.py", line 78, in request
    return await self.connection.request(method, url, headers, stream, timeout)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_async/http11.py", line 62, in request
    ) = await self._receive_response(timeout)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_async/http11.py", line 115, in _receive_response
    event = await self._receive_event(timeout)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_async/http11.py", line 145, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 134, in read
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jugmac00/Tests/sitemaps/sitemaps/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ReadTimeout
```

**Comment by florimondmanca** [comment]
Heya,

Hmm yup, looks like one of the URLs discovered by the crawler is causing a timeout.

Currently `sitemaps` will fail like this instead of silently glossing over the faulty web page. I think when such URLs arise it's fair to add a `-I <url>` flag to ignore it during crawling.

We'd probably want to catch any exceptions when making the web request and log a more helpful error message (which includes the faulty URL).

Right now this would be blocked on https://github.com/encode/httpx/issues/949.

In the meantime you can enable HTTPX debug logs to see the faulty URLs, and add them to as `-I` flags. (Eg I see there's a `/downloads` section on the website. I don't know if it's the one causing a timeout, but in any case you'd probably want to add `-I /downloads/` to not crawl it.)

**Comment by florimondmanca** [comment]
We could probably also add a `--max-depth` option of some sort, and some progress logging to display how the crawling is doing.

**Comment by jugmac00** [comment]
> progress logging

Sounds great! I started another test run on https://blog.fefe.de like 10 minutes ago... and until now zero output :-D

It worked perfect for my simple blog
`python -m sitemaps https://jugmac00.github.io`

Don't do any work as of my issue - I do not need a sitemap crawler - just read your announcement, tried it and thought I report the error.

Cheers!

**Comment by florimondmanca** [comment]
Closing this since it was made obsolete by the new API, which doesn't crawl the app anymore. :-)
